"""Every protein suggest_from_pantry can cook.

Proteins of the same kind cook the same way, so the times and temperatures live in PROFILES and
each protein in PROTEIN_TABLE just names its profile. This file is data only.
"""

# One profile per way of cooking a cut.
#   prep:        what to do before seasoning.
#   safe_temp_f: internal temperature to check for, or None when a thermometer does not apply.
#   methods:     cooking methods that suit the cut, best first, each with its time and temperature.
#   coat:        "mix" when seasoning is stirred in (ground meat, eggs, beans) rather than rubbed on.
#   needs_oil:   False when the cut cooks in its own fat, so a pan needs no added oil.
PROFILES = {
    # --- poultry ---
    "poultry breast": {
        "prep": "Use boneless, skinless meat, and pound thick pieces to an even 3/4 inch.",
        "safe_temp_f": 165,
        "methods": {
            "bake": "425°F for 18-22 min",
            "air-fry": "380°F for 12-15 min, flipping once",
            "grill": "medium-high heat, 5-7 min per side",
            "pan-sear": "medium-high heat, 5-6 min per side",
            "stir-fry": "slice thin, high heat for 4-5 min",
            "poach": "gentle simmer for 12-15 min, then rest 5 min",
            "braise": "simmer covered for 15-20 min",
        },
    },
    "poultry thigh": {
        "prep": "Use boneless, skinless meat and trim the visible fat.",
        "safe_temp_f": 165,
        "methods": {
            "bake": "425°F for 20-25 min",
            "air-fry": "380°F for 16-18 min, flipping once",
            "grill": "medium-high heat, 5-6 min per side",
            "pan-sear": "medium-high heat, 5-6 min per side",
            "stir-fry": "slice thin, high heat for 5-6 min",
            "braise": "simmer covered for 20-25 min",
            "poach": "gentle simmer for 12-15 min, then rest 5 min",
        },
    },
    "poultry cutlet": {
        "prep": "Pat the cutlets dry.",
        "safe_temp_f": 165,
        "methods": {
            "pan-sear": "medium-high heat, 2-3 min per side",
            "bake": "425°F for 8-10 min",
            "grill": "high heat, 2-3 min per side",
            "air-fry": "390°F for 6-8 min",
            "stir-fry": "slice into strips, high heat for 3-4 min",
        },
    },
    "poultry bone-in": {
        "prep": "Pull the skin off to cut the fat, and score the meat so the seasoning gets in.",
        "safe_temp_f": 165,
        "methods": {
            "bake": "425°F for 35-40 min, turning once",
            "air-fry": "380°F for 22-25 min, turning once",
            "grill": "medium heat for 25-30 min, turning often",
            "braise": "simmer covered for 35-40 min",
        },
    },
    "poultry wings": {
        "prep": "Pat very dry so the skin crisps.",
        "safe_temp_f": 165,
        "needs_oil": False,
        "methods": {
            "bake": "425°F for 40-45 min, turning once",
            "air-fry": "380°F for 22-25 min, shaking twice",
            "grill": "medium heat for 20-25 min, turning often",
            "braise": "simmer covered for 25-30 min",
        },
    },
    "large poultry leg": {
        "prep": "Pull the skin off to cut the fat.",
        "safe_temp_f": 165,
        "methods": {
            "bake": "350°F for 1.5-2 hours",
            "braise": "simmer covered for 1.5-2 hours",
            "grill": "indirect medium heat for about 1.5 hours, turning now and then",
        },
    },
    "whole bird": {
        "prep": "Pat dry inside and out.",
        "safe_temp_f": 165,
        "methods": {
            "bake": "425°F for about 15 min per lb, then rest 15 min",
            "grill": "indirect medium heat for about 15 min per lb",
            "braise": "cut into pieces and simmer covered for 45-60 min",
        },
    },
    "whole turkey": {
        "prep": "Thaw fully and pat dry inside and out.",
        "safe_temp_f": 165,
        "methods": {
            "bake": "325°F for about 13-15 min per lb, then rest 30 min",
            "grill": "indirect medium heat for about 13-15 min per lb",
        },
    },
    "small bird": {
        "prep": "Pat dry.",
        "safe_temp_f": 165,
        "methods": {
            "bake": "425°F for 15-20 min",
            "grill": "medium-high heat, 4-5 min per side",
            "pan-sear": "medium-high heat, 4-5 min per side",
            "air-fry": "380°F for 12-15 min",
            "braise": "simmer covered for 25-30 min",
        },
    },
    "duck breast": {
        "prep": "Score the skin in a crosshatch, and pour off the fat as it renders.",
        "safe_temp_f": 165,
        "needs_oil": False,
        "methods": {
            "pan-sear": "skin-side down over medium-low heat for 8-10 min, then 3-4 min on the other side",
            "grill": "medium heat, skin-side down for 6-8 min, then 3-4 min on the other side",
            "bake": "sear skin-side down first, then 400°F for 8-10 min",
        },
    },
    "duck leg": {
        "prep": "Prick the skin all over so the fat can render.",
        "safe_temp_f": 165,
        "needs_oil": False,
        "methods": {
            "braise": "simmer covered for 1.5-2 hours",
            "bake": "325°F for 1.5-2 hours",
        },
    },
    # --- ground meat ---
    "ground meat": {
        "prep": "Choose the leanest grind you can, and drain the rendered fat after browning.",
        "safe_temp_f": 160,
        "coat": "mix",
        "needs_oil": False,
        "methods": {
            "stir-fry": "crumble over high heat for 5-7 min, then drain the fat",
            "pan-sear": "shape into patties, 4 min per side",
            "bake": "roll into meatballs, 400°F for 15-18 min",
            "air-fry": "roll into meatballs, 380°F for 10-12 min",
            "grill": "shape into patties, medium-high heat, 4-5 min per side",
            "braise": "brown and drain, then simmer for 15 min",
        },
    },
    "ground poultry": {
        "prep": "Choose the leanest grind you can.",
        "safe_temp_f": 165,
        "coat": "mix",
        "methods": {
            "stir-fry": "crumble over high heat for 6-8 min",
            "pan-sear": "shape into patties, 5 min per side",
            "bake": "roll into meatballs, 400°F for 18-20 min",
            "air-fry": "roll into meatballs, 380°F for 10-12 min",
            "grill": "shape into patties, medium-high heat, 5-6 min per side",
            "braise": "brown, then simmer for 15 min",
        },
    },
    # --- beef, veal, lamb, game: whole cuts ---
    "steak": {
        "prep": "Trim the outer fat and let it sit at room temperature for 20 min.",
        "safe_temp_f": 145,
        "methods": {
            "pan-sear": "high heat, 3-4 min per side, then rest 5 min",
            "grill": "high heat, 3-5 min per side, then rest 5 min",
            "bake": "sear first, then 400°F for 5-8 min",
            "air-fry": "400°F for 8-12 min, flipping once",
            "stir-fry": "slice thin against the grain, high heat for 2-3 min",
        },
    },
    "game steak": {
        "prep": "Trim all the fat and silverskin. Game is lean, so do not overcook it.",
        "safe_temp_f": 160,
        "methods": {
            "pan-sear": "high heat, 3-4 min per side, then rest 5 min",
            "grill": "high heat, 3-4 min per side, then rest 5 min",
            "bake": "sear first, then 400°F for 5-8 min",
            "stir-fry": "slice thin against the grain, high heat for 2-3 min",
            "braise": "cube, then simmer covered for 1.5-2 hours",
        },
    },
    "thin cutlet": {
        "prep": "Pat the cutlets dry.",
        "safe_temp_f": 145,
        "methods": {
            "pan-sear": "medium-high heat, 2-3 min per side",
            "grill": "high heat, 2 min per side",
            "bake": "425°F for 8-10 min",
            "air-fry": "390°F for 6-8 min",
            "stir-fry": "slice into strips, high heat for 2-3 min",
        },
    },
    "tough cut": {
        "prep": "Trim the surface fat and cut large pieces into chunks.",
        "safe_temp_f": 145,
        "methods": {
            "braise": "simmer covered for 2.5-3 hours, until fork-tender",
            "bake": "covered at 325°F for 3-3.5 hours, until fork-tender",
        },
    },
    "stew meat": {
        "prep": "Trim the fat and cut into 1-inch cubes.",
        "safe_temp_f": 145,
        "methods": {
            "braise": "simmer covered for 1.5-2 hours, until tender",
            "bake": "covered at 325°F for 2-2.5 hours, until tender",
        },
    },
    "tender roast": {
        "prep": "Trim the fat cap and let it sit at room temperature for 30 min.",
        "safe_temp_f": 145,
        "methods": {
            "bake": "450°F for 15 min, then 325°F for about 15-20 min per lb, then rest 15 min",
            "grill": "indirect medium heat for about 15-20 min per lb, then rest 15 min",
        },
    },
    "ribs": {
        "prep": "Peel the membrane off the bone side and trim the surface fat.",
        "safe_temp_f": 145,
        "needs_oil": False,
        "methods": {
            "bake": "wrapped in foil at 300°F for 2.5-3 hours, then uncovered at 425°F for 10 min",
            "grill": "indirect low heat for 2.5-3 hours, turning now and then",
            "braise": "simmer covered for 1.5-2 hours, until tender",
            "air-fry": "cut into sections, 375°F for 25-30 min, turning once",
        },
    },
    # --- pork ---
    "pork loin": {
        "prep": "Trim the fat cap and cut into 1-inch medallions.",
        "safe_temp_f": 145,
        "methods": {
            "bake": "400°F for 15-18 min, then rest 3 min",
            "air-fry": "380°F for 10-12 min, flipping once",
            "grill": "medium-high heat, 4-5 min per side",
            "pan-sear": "medium-high heat, 3-4 min per side",
            "stir-fry": "slice thin, high heat for 3-4 min",
            "braise": "cube, then simmer covered for 30-40 min",
        },
    },
    "pork chop": {
        "prep": "Trim the fat edge.",
        "safe_temp_f": 145,
        "methods": {
            "bake": "400°F for 15-18 min, then rest 3 min",
            "air-fry": "380°F for 10-12 min, flipping once",
            "grill": "medium-high heat, 4-5 min per side",
            "pan-sear": "medium-high heat, 4-5 min per side",
            "braise": "simmer covered for 25-30 min",
        },
    },
    "pork belly": {
        "prep": "Score the skin and pour off the fat as it renders.",
        "safe_temp_f": 145,
        "needs_oil": False,
        "methods": {
            "bake": "400°F for 45-60 min",
            "braise": "simmer covered for about 1.5 hours",
            "air-fry": "cube, 390°F for 15-18 min",
            "pan-sear": "slice 1/4 inch thick, medium heat for 3-4 min per side",
        },
    },
    "bacon": {
        "prep": "Blot the cooked slices on paper towels.",
        "safe_temp_f": None,
        "needs_oil": False,
        "methods": {
            "bake": "400°F for 15-20 min on a rack",
            "pan-sear": "medium heat for 8-10 min, turning",
            "air-fry": "370°F for 8-10 min",
        },
    },
    "sausage": {
        "prep": "Prick each sausage once or twice.",
        "safe_temp_f": 160,
        "needs_oil": False,
        "methods": {
            "bake": "400°F for 20-25 min, turning once",
            "pan-sear": "medium heat for 12-15 min, turning often",
            "grill": "medium heat for 15-20 min, turning often",
            "air-fry": "370°F for 10-12 min",
            "poach": "simmer for 10-12 min",
            "braise": "simmer for 10 min, then brown",
        },
    },
    "poultry sausage": {
        "prep": "Prick each sausage once or twice.",
        "safe_temp_f": 165,
        "methods": {
            "bake": "400°F for 18-22 min, turning once",
            "pan-sear": "medium heat for 10-12 min, turning often",
            "grill": "medium heat for 12-15 min, turning often",
            "air-fry": "370°F for 10-12 min",
            "poach": "simmer for 10-12 min",
        },
    },
    "cooked sausage": {
        "prep": "It is already cooked, so it only needs heating through.",
        "safe_temp_f": None,
        "needs_oil": False,
        "methods": {
            "pan-sear": "medium heat for 5-6 min, until browned",
            "grill": "medium heat for 5-7 min, turning",
            "stir-fry": "slice, high heat for 3-4 min",
            "bake": "400°F for 10-12 min",
            "air-fry": "370°F for 6-8 min",
            "poach": "simmer for 5 min",
            "braise": "simmer in the liquid for 10 min",
        },
    },
    "ham": {
        "prep": "It is already cooked, so it only needs heating through.",
        "safe_temp_f": 140,
        "needs_oil": False,
        "methods": {
            "pan-sear": "medium-high heat, 3-4 min per side",
            "bake": "325°F for about 10 min per lb",
            "grill": "medium heat, 3-4 min per side",
            "no-cook": "ready to eat, sliced or diced",
        },
    },
    # --- organ meat ---
    "liver": {
        "prep": "Trim the membranes and soak in cold water for 20 min, then pat dry.",
        "safe_temp_f": 160,
        "methods": {
            "pan-sear": "medium-high heat, 2-3 min per side",
            "grill": "high heat, 2-3 min per side",
            "stir-fry": "slice thin, high heat for 2-3 min",
            "braise": "simmer for 10-15 min",
        },
    },
    "poultry liver": {
        "prep": "Trim the membranes and pat dry.",
        "safe_temp_f": 165,
        "methods": {
            "pan-sear": "medium-high heat, 2-3 min per side",
            "stir-fry": "high heat for 3-4 min",
            "braise": "simmer for 10-15 min",
            "grill": "skewer, high heat for 2-3 min per side",
        },
    },
    "tough organ": {
        "prep": "Rinse well and trim.",
        "safe_temp_f": 160,
        "methods": {
            "braise": "simmer covered for 2-3 hours, until tender",
            "bake": "covered at 325°F for 2.5-3 hours, until tender",
        },
    },
    "kidney": {
        "prep": "Halve, cut out the white core, and soak in cold water for 30 min.",
        "safe_temp_f": 160,
        "methods": {
            "pan-sear": "medium-high heat, 3-4 min per side",
            "braise": "simmer covered for 45-60 min",
            "grill": "skewer, high heat for 3-4 min per side",
        },
    },
    # --- fish ---
    "lean fish": {
        "prep": "Pat the fillets dry.",
        "safe_temp_f": 145,
        "methods": {
            "bake": "400°F for 10-12 min",
            "air-fry": "390°F for 8-10 min",
            "pan-sear": "medium-high heat, 3-4 min per side",
            "poach": "gentle simmer for 5-6 min",
            "steam": "6-8 min",
            "grill": "medium-high heat in a fish basket, 3-4 min per side",
            "braise": "simmer gently in the sauce for 6-8 min",
        },
    },
    "oily fish": {
        "prep": "Pat the fillets dry. Skin-on is fine.",
        "safe_temp_f": 145,
        "needs_oil": False,
        "methods": {
            "bake": "400°F for 12-15 min",
            "air-fry": "390°F for 8-10 min",
            "grill": "medium-high heat, 4-5 min per side",
            "pan-sear": "skin-side down for 4-5 min, then 2-3 min on the other side",
            "poach": "gentle simmer for 8-10 min",
            "steam": "8-10 min",
        },
    },
    "fish steak": {
        "prep": "Pat dry.",
        "safe_temp_f": 145,
        "methods": {
            "grill": "high heat, 3-4 min per side",
            "pan-sear": "high heat, 3-4 min per side",
            "bake": "400°F for 10-12 min",
            "air-fry": "390°F for 8-10 min",
            "poach": "gentle simmer for 8-10 min",
        },
    },
    "small fish": {
        "prep": "Clean and pat dry.",
        "safe_temp_f": 145,
        "needs_oil": False,
        "methods": {
            "grill": "high heat, 2-4 min per side",
            "bake": "425°F for 10-15 min",
            "pan-sear": "medium-high heat, 2-3 min per side",
            "air-fry": "390°F for 8-10 min",
        },
    },
    "whole fish": {
        "prep": "Scale and gut it, then cut three slashes in each side.",
        "safe_temp_f": 145,
        "methods": {
            "bake": "425°F for 20-25 min",
            "grill": "medium-high heat, 6-8 min per side",
            "steam": "12-15 min",
            "braise": "simmer gently in the sauce for 15-20 min",
        },
    },
    # --- shellfish ---
    "shrimp": {
        "prep": "Peel, devein and pat very dry.",
        "safe_temp_f": None,
        "methods": {
            "stir-fry": "high heat for 2-3 min, until pink and opaque",
            "pan-sear": "high heat, 1-2 min per side",
            "grill": "skewer, high heat for 2 min per side",
            "air-fry": "400°F for 5-6 min",
            "bake": "400°F for 6-8 min",
            "poach": "simmer for 2-3 min, until pink and opaque",
            "steam": "3-4 min, until pink and opaque",
        },
    },
    "scallop": {
        "prep": "Pull off the side muscle and pat very dry.",
        "safe_temp_f": None,
        "methods": {
            "pan-sear": "very hot pan, 1.5-2 min per side",
            "grill": "skewer, high heat for 2 min per side",
            "bake": "400°F for 10-12 min",
            "air-fry": "400°F for 5-6 min",
            "stir-fry": "high heat for 2-3 min",
            "poach": "simmer for 2-3 min",
            "steam": "3-4 min",
        },
    },
    "lobster": {
        "prep": "Split the tails down the back and lift the meat onto the shell.",
        "safe_temp_f": 145,
        "methods": {
            "steam": "8-10 min for tails, or 10-12 min per lb for a whole lobster",
            "bake": "425°F for 10-12 min for split tails",
            "grill": "medium-high heat, 5-6 min flesh-side down, then 3-4 min",
            "poach": "simmer for 5-6 min for tails",
        },
    },
    "crab": {
        "prep": "Rinse the shells.",
        "safe_temp_f": 145,
        "methods": {
            "steam": "5-7 min for cooked legs, or 15-20 min for a live crab",
            "bake": "375°F for 10 min for cooked legs",
            "poach": "simmer for 4-5 min for cooked legs",
            "grill": "medium heat for 5-6 min for cooked legs",
        },
    },
    "crawfish": {
        "prep": "Rinse well.",
        "safe_temp_f": None,
        "methods": {
            "poach": "boil for 3-5 min, until bright red",
            "steam": "5-6 min, until bright red",
            "stir-fry": "peeled tails, high heat for 2-3 min",
        },
    },
    "bivalve": {
        "prep": "Scrub the shells and throw out any that are cracked or will not close.",
        "safe_temp_f": None,
        "methods": {
            "steam": "5-7 min, until the shells open; throw out any that stay shut",
            "braise": "simmer covered in the liquid for 5-7 min, until the shells open",
            "grill": "high heat for 5-8 min, until the shells open",
            "bake": "450°F for 8-10 min, until the shells open",
        },
    },
    "squid": {
        "prep": "Clean it, then cut into rings or score the bodies.",
        "safe_temp_f": None,
        "methods": {
            "stir-fry": "high heat for 1-2 min; any longer turns it rubbery",
            "grill": "high heat, 1-2 min per side",
            "pan-sear": "high heat for 1-2 min",
            "poach": "simmer for 1-2 min",
            "braise": "simmer for 30-40 min, until tender",
        },
    },
    "octopus": {
        "prep": "Rinse well and remove the beak.",
        "safe_temp_f": None,
        "methods": {
            "braise": "simmer for 45-60 min, until a knife slides in",
            "poach": "simmer for 45-60 min, until a knife slides in",
            "grill": "simmer until tender first, then high heat for 3-4 min per side",
        },
    },
    "snail": {
        "prep": "Rinse well.",
        "safe_temp_f": None,
        "methods": {
            "braise": "simmer for 15-20 min",
            "bake": "400°F for 10-12 min",
            "stir-fry": "high heat for 3-4 min",
        },
    },
    # --- ready to eat ---
    "ready to eat": {
        "prep": "Drain it well.",
        "safe_temp_f": None,
        "coat": "mix",
        "needs_oil": False,
        "methods": {
            "no-cook": "ready to eat once drained and flaked",
            "stir-fry": "add at the end and warm through for 1-2 min",
            "pan-sear": "medium heat for 2-3 min, to warm it and crisp the edges",
            "bake": "400°F for 8-10 min, to warm through",
        },
    },
    # --- eggs ---
    "eggs": {
        "prep": "Crack into a bowl.",
        "safe_temp_f": None,
        "coat": "mix",
        "methods": {
            "pan-sear": "scramble or fry over medium-low heat for 2-3 min, until set",
            "stir-fry": "scramble in the hot pan for 1-2 min, until set",
            "poach": "3-4 min in barely simmering water, or boil in the shell for 10-12 min",
            "steam": "beat with water and steam for 8-10 min, until just set",
            "bake": "375°F for 12-15 min in a small dish, until set",
            "braise": "crack into the simmering liquid, cover, and cook for 5-7 min",
        },
    },
    # --- plant proteins ---
    "tofu": {
        "prep": "Press firm tofu for 15 min to drain it, then cut into slabs or cubes.",
        "safe_temp_f": None,
        "methods": {
            "bake": "400°F for 25-30 min, turning once",
            "air-fry": "380°F for 12-15 min, shaking once",
            "pan-sear": "medium-high heat, 3-4 min per side",
            "stir-fry": "high heat for 5-6 min",
            "braise": "simmer gently for 10 min",
            "steam": "8-10 min",
        },
    },
    "soft tofu": {
        "prep": "Drain gently; it breaks easily.",
        "safe_temp_f": None,
        "methods": {
            "steam": "8-10 min",
            "braise": "simmer gently for 5 min",
            "poach": "simmer for 3-4 min",
            "no-cook": "ready to eat, drained and sliced",
        },
    },
    "tempeh": {
        "prep": "Steam for 10 min first to mellow the bitterness, then slice.",
        "safe_temp_f": None,
        "methods": {
            "bake": "400°F for 20-25 min, turning once",
            "air-fry": "380°F for 10-12 min",
            "pan-sear": "medium-high heat, 3-4 min per side",
            "grill": "medium-high heat, 3-4 min per side",
            "stir-fry": "high heat for 5-6 min",
            "braise": "simmer for 10-15 min",
            "steam": "10 min",
        },
    },
    "seitan": {
        "prep": "Slice or tear into pieces.",
        "safe_temp_f": None,
        "methods": {
            "bake": "375°F for 20 min",
            "air-fry": "380°F for 8-10 min",
            "grill": "medium-high heat, 3-4 min per side",
            "pan-sear": "medium-high heat, 3-4 min per side",
            "stir-fry": "high heat for 4-5 min",
            "braise": "simmer for 15 min",
        },
    },
    "plant crumbles": {
        "prep": "Rehydrate dry crumbles in hot water for 10 min, then squeeze dry.",
        "safe_temp_f": None,
        "coat": "mix",
        "methods": {
            "stir-fry": "high heat for 5-6 min",
            "pan-sear": "shape into patties, 4 min per side",
            "bake": "roll into balls, 400°F for 15-18 min",
            "braise": "simmer for 10 min",
        },
    },
    "veggie patty": {
        "prep": "Cook from frozen or thawed.",
        "safe_temp_f": None,
        "methods": {
            "bake": "400°F for 15-18 min, flipping once",
            "air-fry": "380°F for 10-12 min",
            "grill": "medium heat, 4-5 min per side",
            "pan-sear": "medium heat, 4-5 min per side",
        },
    },
    "legume": {
        "prep": "Use cooked or canned, drained and rinsed.",
        "safe_temp_f": None,
        "coat": "mix",
        "methods": {
            "braise": "simmer in the liquid for 10-15 min",
            "bake": "400°F for 20-25 min, until crisp at the edges",
            "air-fry": "390°F for 12-15 min, shaking once",
            "stir-fry": "high heat for 3-4 min",
            "pan-sear": "medium-high heat for 5-6 min",
            "steam": "5 min, to warm through",
            "poach": "simmer for 5 min, to warm through",
            "no-cook": "ready to eat once drained and rinsed",
        },
    },
    # --- dairy ---
    "grilling cheese": {
        "prep": "Cut into 1/2-inch slabs and pat dry.",
        "safe_temp_f": None,
        "needs_oil": False,
        "methods": {
            "grill": "medium-high heat, 2-3 min per side",
            "pan-sear": "medium-high heat, 2-3 min per side",
            "bake": "400°F for 12-15 min",
            "air-fry": "390°F for 6-8 min",
            "stir-fry": "cube, high heat for 2-3 min",
            "braise": "simmer gently for 5 min",
        },
    },
    "soft dairy": {
        "prep": "Spoon into a bowl.",
        "safe_temp_f": None,
        "coat": "mix",
        "methods": {"no-cook": "ready to eat"},
    },
}

# What to do with a protein that is not in the table but that USDA confirms is protein-rich.
GENERIC_PROFILE = {
    "prep": "Pat dry.",
    "safe_temp_f": None,
    "kind": "other",
    "methods": {
        "bake": "400°F until cooked through; the time depends on the cut",
        "grill": "medium-high heat until cooked through",
        "pan-sear": "medium-high heat until cooked through",
        "stir-fry": "cut small, high heat until cooked through",
        "braise": "simmer covered until tender",
        "steam": "until cooked through",
        "poach": "simmer until cooked through",
        "air-fry": "380°F until cooked through",
    },
}

# name: (profile, kind, USDA search text). Flavor bases in pantry_rules say which kinds they suit.
# USDA's lab-analysed data has no usable entry for oxtail, seitan, soy crumbles, paneer, halloumi
# or deli roast beef, so their nutrition lookups come back "not found" rather than borrowing
# another food's numbers.
PROTEIN_TABLE = {
    # --- chicken ---
    "chicken breast": ("poultry breast", "poultry", "chicken breast boneless skinless raw"),
    "chicken tenders": ("poultry cutlet", "poultry", "chicken breast boneless skinless raw"),
    "chicken thigh": ("poultry thigh", "poultry", "chicken thigh boneless skinless raw"),
    "bone-in chicken thigh": ("poultry bone-in", "poultry", "chicken thigh meat and skin raw"),
    "chicken drumstick": ("poultry bone-in", "poultry", "chicken drumstick meat only raw"),
    "chicken leg quarter": ("poultry bone-in", "poultry", "chicken broilers or fryers leg meat and skin raw"),
    "chicken wings": ("poultry wings", "poultry", "chicken broilers or fryers wing meat and skin raw"),
    "whole chicken": ("whole bird", "poultry", "chicken broilers or fryers meat and skin raw"),
    "cornish hen": ("whole bird", "poultry", "chicken cornish game hens meat and skin raw"),
    "ground chicken": ("ground poultry", "poultry", "chicken ground raw"),
    "chicken sausage": ("poultry sausage", "poultry", "sausage chicken or turkey italian style lower sodium"),
    "chicken liver": ("poultry liver", "offal", "chicken liver all classes raw"),
    "chicken heart": ("poultry liver", "offal", "chicken heart all classes raw"),
    "chicken gizzard": ("tough organ", "offal", "chicken gizzard all classes raw"),
    # --- turkey ---
    "turkey breast": ("poultry breast", "poultry", "turkey whole breast meat only raw"),
    "turkey cutlet": ("poultry cutlet", "poultry", "turkey whole breast meat only raw"),
    "turkey thigh": ("large poultry leg", "poultry", "turkey whole thigh meat only raw"),
    "turkey drumstick": ("large poultry leg", "poultry", "turkey whole drumstick meat only raw"),
    "turkey wings": ("large poultry leg", "poultry", "turkey whole wing meat only raw"),
    "whole turkey": ("whole turkey", "poultry", "turkey whole meat only raw"),
    "ground turkey": ("ground poultry", "poultry", "turkey ground 93% lean 7% fat raw"),
    "turkey sausage": ("poultry sausage", "poultry", "turkey sausage fresh raw"),
    "turkey bacon": ("bacon", "poultry", "bacon turkey unprepared"),
    # --- duck, goose and other birds ---
    "duck breast": ("duck breast", "poultry", "duck domesticated meat only raw"),
    "duck leg": ("duck leg", "poultry", "duck domesticated meat and skin raw"),
    "whole duck": ("whole bird", "poultry", "duck domesticated meat and skin raw"),
    "goose": ("whole bird", "poultry", "goose domesticated meat only raw"),
    "quail": ("small bird", "poultry", "quail meat and skin raw"),
    "squab": ("small bird", "poultry", "squab (pigeon) meat and skin raw"),
    "pheasant": ("whole bird", "poultry", "pheasant raw meat only"),
    "guinea fowl": ("whole bird", "poultry", "guinea hen meat only raw"),
    "ostrich": ("game steak", "game", "ostrich top loin raw"),
    "emu": ("game steak", "game", "emu fan fillet raw"),
    # --- beef ---
    "ground beef": ("ground meat", "beef", "beef ground 90% lean raw"),
    "sirloin steak": ("steak", "beef", "beef top sirloin steak separable lean only raw"),
    "ribeye steak": ("steak", "beef", "beef rib eye steak boneless lip off separable lean only raw"),
    "strip steak": ("steak", "beef", "beef loin top loin steak boneless lip off separable lean only raw"),
    "filet mignon": ("steak", "beef", "beef tenderloin steak separable lean only raw"),
    "t-bone steak": ("steak", "beef", "beef short loin t-bone steak separable lean only raw"),
    "porterhouse steak": ("steak", "beef", "beef short loin porterhouse steak separable lean only raw"),
    "flank steak": ("steak", "beef", "beef flank steak separable lean only raw"),
    "skirt steak": ("steak", "beef", "beef plate steak inside skirt separable lean only raw"),
    "round steak": ("steak", "beef", "beef round top round steak separable lean only raw"),
    "tri-tip": ("tender roast", "beef", "beef bottom sirloin tri-tip roast separable lean only raw"),
    "beef tenderloin roast": ("tender roast", "beef", "beef tenderloin roast separable lean only raw"),
    "prime rib": ("tender roast", "beef", "beef rib eye roast boneless lip-on separable lean only raw"),
    "eye of round roast": ("tender roast", "beef", "beef round eye of round roast separable lean only raw"),
    "bottom round roast": ("tender roast", "beef", "beef round bottom round roast separable lean only raw"),
    "chuck roast": ("tough cut", "beef", "beef chuck arm pot roast separable lean only raw"),
    "brisket": ("tough cut", "beef", "beef brisket whole separable lean only raw"),
    "short ribs": ("tough cut", "beef", "beef chuck short ribs boneless separable lean only raw"),
    "beef back ribs": ("ribs", "beef", "beef rib back ribs bone-in separable lean only raw"),
    "beef shank": ("tough cut", "beef", "beef shank crosscuts separable lean only raw"),
    "oxtail": ("tough cut", "beef", "oxtail raw"),
    "beef stew meat": ("stew meat", "beef", "beef chuck for stew separable lean and fat raw"),
    "corned beef": ("tough cut", "beef", "beef cured corned beef brisket raw"),
    "beef liver": ("liver", "offal", "beef variety meats and by-products liver raw"),
    "beef heart": ("tough organ", "offal", "beef variety meats and by-products heart raw"),
    "beef tongue": ("tough organ", "offal", "beef variety meats and by-products tongue raw"),
    "beef kidney": ("kidney", "offal", "beef variety meats and by-products kidneys raw"),
    "tripe": ("tough organ", "offal", "beef variety meats and by-products tripe raw"),
    # --- veal ---
    "veal cutlet": ("thin cutlet", "beef", "veal leg (top round) separable lean only raw"),
    "veal chop": ("steak", "beef", "veal loin separable lean only raw"),
    "ground veal": ("ground meat", "beef", "veal ground raw"),
    "veal shank": ("tough cut", "beef", "veal shank (fore and hind) separable lean only raw"),
    "calf liver": ("liver", "offal", "veal variety meats and by-products liver raw"),
    # --- pork ---
    "pork chop": ("pork chop", "pork", "pork loin top loin chops boneless separable lean only raw"),
    "pork loin": ("pork loin", "pork", "pork loin top loin roasts boneless separable lean only raw"),
    "pork tenderloin": ("pork loin", "pork", "pork fresh loin tenderloin separable lean only raw"),
    "pork cutlet": ("thin cutlet", "pork", "pork fresh loin sirloin (chops) boneless separable lean only raw"),
    "pork ribs": ("ribs", "pork", "pork fresh spareribs separable lean and fat raw"),
    "baby back ribs": ("ribs", "pork", "pork fresh backribs separable lean and fat raw"),
    "country-style ribs": ("ribs", "pork", "pork fresh loin country-style ribs separable lean only raw"),
    "pork shoulder": ("tough cut", "pork", "pork fresh shoulder whole separable lean only raw"),
    "pork belly": ("pork belly", "pork", "pork fresh belly raw"),
    "ground pork": ("ground meat", "pork", "pork fresh ground raw"),
    "fresh ham": ("tender roast", "pork", "pork fresh leg (ham) whole separable lean only raw"),
    "ham": ("ham", "pork", "ham sliced regular"),
    "bacon": ("bacon", "pork", "pork cured bacon unprepared"),
    "canadian bacon": ("ham", "pork", "canadian bacon unprepared"),
    "pork sausage": ("sausage", "pork", "pork sausage link/patty unprepared"),
    "italian sausage": ("sausage", "pork", "sausage italian pork raw"),
    "bratwurst": ("sausage", "pork", "bratwurst pork cooked"),
    "chorizo": ("sausage", "pork", "sausage pork chorizo link or ground raw"),
    "kielbasa": ("cooked sausage", "pork", "sausage polish pork and beef smoked"),
    "smoked sausage": ("cooked sausage", "pork", "sausage smoked link sausage pork"),
    "hot dog": ("cooked sausage", "pork", "frankfurter beef unheated"),
    "pork liver": ("liver", "offal", "pork fresh variety meats and by-products liver raw"),
    # --- lamb and goat ---
    "lamb chops": ("steak", "lamb", "lamb loin separable lean only choice raw"),
    "rack of lamb": ("tender roast", "lamb", "lamb rib separable lean only choice raw"),
    "leg of lamb": ("tender roast", "lamb", "lamb leg whole shank and sirloin separable lean only choice raw"),
    "lamb shank": ("tough cut", "lamb", "lamb foreshank separable lean only choice raw"),
    "lamb shoulder": ("tough cut", "lamb", "lamb shoulder whole arm and blade separable lean only choice raw"),
    "lamb stew meat": ("stew meat", "lamb", "lamb cubed for stew or kabob separable lean only raw"),
    "ground lamb": ("ground meat", "lamb", "lamb ground raw"),
    "lamb liver": ("liver", "offal", "lamb variety meats and by-products liver raw"),
    "goat": ("stew meat", "lamb", "game meat goat raw"),
    # --- game ---
    "venison": ("game steak", "game", "game meat deer raw"),
    "ground venison": ("ground meat", "game", "game meat deer ground raw"),
    "elk": ("game steak", "game", "game meat elk raw"),
    "ground elk": ("ground meat", "game", "game meat elk ground raw"),
    "bison steak": ("steak", "game", "game meat bison top sirloin separable lean only trimmed to 0 fat raw"),
    "ground bison": ("ground meat", "game", "game meat bison ground raw"),
    "wild boar": ("game steak", "game", "game meat boar wild raw"),
    "rabbit": ("stew meat", "game", "game meat rabbit domesticated composite of cuts raw"),
    "moose": ("game steak", "game", "game meat moose raw"),
    "caribou": ("game steak", "game", "game meat caribou raw"),
    "antelope": ("game steak", "game", "game meat antelope raw"),
    "bear": ("stew meat", "game", "game meat bear raw"),
    "squirrel": ("stew meat", "game", "game meat squirrel raw"),
    "horse": ("game steak", "game", "game meat horse raw"),
    "frog legs": ("small bird", "game", "frog legs raw"),
    "turtle": ("stew meat", "game", "turtle green raw"),
    # --- lean white fish ---
    "tilapia": ("lean fish", "lean fish", "tilapia raw"),
    "cod": ("lean fish", "lean fish", "cod atlantic raw"),
    "haddock": ("lean fish", "lean fish", "fish haddock raw"),
    "pollock": ("lean fish", "lean fish", "fish pollock atlantic raw"),
    "halibut": ("lean fish", "lean fish", "fish halibut atlantic and pacific raw"),
    "flounder": ("lean fish", "lean fish", "fish flatfish (flounder and sole species) raw"),
    "catfish": ("lean fish", "lean fish", "fish catfish channel farmed raw"),
    "sea bass": ("lean fish", "lean fish", "fish sea bass mixed species raw"),
    "striped bass": ("lean fish", "lean fish", "fish bass striped raw"),
    "snapper": ("lean fish", "lean fish", "fish snapper mixed species raw"),
    "grouper": ("lean fish", "lean fish", "fish grouper mixed species raw"),
    "mahi mahi": ("lean fish", "lean fish", "fish mahimahi raw"),
    "perch": ("lean fish", "lean fish", "fish perch mixed species raw"),
    "walleye": ("lean fish", "lean fish", "fish pike walleye raw"),
    "pike": ("lean fish", "lean fish", "fish pike northern raw"),
    "whiting": ("lean fish", "lean fish", "fish whiting mixed species raw"),
    "monkfish": ("lean fish", "lean fish", "fish monkfish raw"),
    "orange roughy": ("lean fish", "lean fish", "fish roughy orange raw"),
    "rockfish": ("lean fish", "lean fish", "fish rockfish pacific mixed species raw"),
    "turbot": ("lean fish", "lean fish", "fish turbot european raw"),
    "carp": ("lean fish", "lean fish", "fish carp raw"),
    "tilefish": ("lean fish", "lean fish", "fish tilefish raw"),
    "croaker": ("lean fish", "lean fish", "fish croaker atlantic raw"),
    "mullet": ("lean fish", "lean fish", "fish mullet striped raw"),
    "pompano": ("lean fish", "lean fish", "fish pompano florida raw"),
    "lingcod": ("lean fish", "lean fish", "fish lingcod raw"),
    "whitefish": ("lean fish", "lean fish", "fish whitefish mixed species raw"),
    "drum": ("lean fish", "lean fish", "fish drum freshwater raw"),
    "wolffish": ("lean fish", "lean fish", "fish wolffish atlantic raw"),
    "whole fish": ("whole fish", "lean fish", "fish snapper mixed species raw"),
    # --- oily fish ---
    "salmon": ("oily fish", "oily fish", "salmon atlantic raw"),
    "trout": ("oily fish", "oily fish", "fish trout rainbow farmed raw"),
    "mackerel": ("oily fish", "oily fish", "fish mackerel atlantic raw"),
    "bluefish": ("oily fish", "oily fish", "fish bluefish raw"),
    "sablefish": ("oily fish", "oily fish", "fish sablefish raw"),
    "herring": ("small fish", "oily fish", "fish herring atlantic raw"),
    "shad": ("oily fish", "oily fish", "fish shad american raw"),
    "eel": ("oily fish", "oily fish", "fish eel mixed species raw"),
    "yellowtail": ("oily fish", "oily fish", "fish yellowtail mixed species raw"),
    "butterfish": ("small fish", "oily fish", "fish butterfish raw"),
    "milkfish": ("oily fish", "oily fish", "fish milkfish raw"),
    "smelt": ("small fish", "oily fish", "fish smelt rainbow raw"),
    "fresh anchovies": ("small fish", "oily fish", "fish anchovy european raw"),
    # --- fish steaks ---
    "tuna steak": ("fish steak", "oily fish", "fish tuna fresh yellowfin raw"),
    "bluefin tuna": ("fish steak", "oily fish", "fish tuna fresh bluefin raw"),
    "swordfish": ("fish steak", "oily fish", "fish swordfish raw"),
    "shark": ("fish steak", "lean fish", "fish shark mixed species raw"),
    "sturgeon": ("fish steak", "oily fish", "fish sturgeon mixed species raw"),
    # --- shellfish ---
    "shrimp": ("shrimp", "shellfish", "shrimp raw"),
    "scallops": ("scallop", "shellfish", "mollusks scallop mixed species raw"),
    "lobster": ("lobster", "shellfish", "crustaceans lobster northern raw"),
    "spiny lobster": ("lobster", "shellfish", "crustaceans spiny lobster mixed species raw"),
    "crab": ("crab", "shellfish", "crustaceans crab blue raw"),
    "king crab": ("crab", "shellfish", "crustaceans crab alaska king raw"),
    "snow crab": ("crab", "shellfish", "crustaceans crab queen raw"),
    "dungeness crab": ("crab", "shellfish", "crustaceans crab dungeness raw"),
    "crawfish": ("crawfish", "shellfish", "crustaceans crayfish mixed species farmed raw"),
    "mussels": ("bivalve", "shellfish", "mollusks mussel blue raw"),
    "clams": ("bivalve", "shellfish", "mollusks clam mixed species raw"),
    "oysters": ("bivalve", "shellfish", "mollusks oyster eastern wild raw"),
    "squid": ("squid", "shellfish", "mollusks squid mixed species raw"),
    "cuttlefish": ("squid", "shellfish", "mollusks cuttlefish mixed species raw"),
    "octopus": ("octopus", "shellfish", "mollusks octopus common raw"),
    "abalone": ("scallop", "shellfish", "mollusks abalone mixed species raw"),
    "whelk": ("snail", "shellfish", "mollusks whelk unspecified raw"),
    "snails": ("snail", "shellfish", "mollusks snail raw"),
    # --- canned, smoked and other ready-to-eat ---
    "canned tuna": ("ready to eat", "ready", "fish tuna light canned in water drained solids"),
    "canned salmon": ("ready to eat", "ready", "fish salmon pink canned drained solids"),
    "canned sardines": ("ready to eat", "ready", "fish sardine atlantic canned in oil drained solids with bone"),
    "canned mackerel": ("ready to eat", "ready", "fish mackerel jack canned drained solids"),
    "canned anchovies": ("ready to eat", "ready", "fish anchovy european canned in oil drained solids"),
    "canned chicken": ("ready to eat", "ready", "chicken canned meat only with broth"),
    "canned crab": ("ready to eat", "ready", "crustaceans crab blue canned"),
    "canned clams": ("ready to eat", "ready", "mollusks clam mixed species canned drained solids"),
    "smoked salmon": ("ready to eat", "ready", "fish salmon chinook smoked"),
    "imitation crab": ("ready to eat", "ready", "crustaceans crab alaska king imitation made from surimi"),
    "rotisserie chicken": ("ready to eat", "ready", "chicken broilers or fryers rotisserie original seasoning breast meat only cooked"),
    "deli turkey": ("ready to eat", "ready", "turkey breast sliced prepackaged"),
    "deli roast beef": ("ready to eat", "ready", "lunchmeat roast beef sliced prepackaged"),
    # --- eggs ---
    "eggs": ("eggs", "egg", "egg whole raw fresh"),
    "egg whites": ("eggs", "egg", "egg white raw fresh"),
    "duck eggs": ("eggs", "egg", "egg duck whole fresh raw"),
    "quail eggs": ("eggs", "egg", "egg quail whole fresh raw"),
    # --- plant proteins ---
    "tofu": ("tofu", "plant", "tofu raw firm prepared with calcium sulfate"),
    "silken tofu": ("soft tofu", "plant", "tofu soft prepared with calcium sulfate and magnesium chloride (nigari)"),
    "tempeh": ("tempeh", "plant", "tempeh"),
    "seitan": ("seitan", "plant", "seitan"),
    "soy crumbles": ("plant crumbles", "plant", "textured vegetable protein"),
    "veggie burger": ("veggie patty", "plant", "veggie burgers or soyburgers unprepared"),
    "edamame": ("legume", "legume", "edamame frozen prepared"),
    "black beans": ("legume", "legume", "beans black mature seeds cooked boiled without salt"),
    "kidney beans": ("legume", "legume", "beans kidney all types mature seeds cooked boiled without salt"),
    "pinto beans": ("legume", "legume", "beans pinto mature seeds cooked boiled without salt"),
    "white beans": ("legume", "legume", "beans white mature seeds cooked boiled without salt"),
    "navy beans": ("legume", "legume", "beans navy mature seeds cooked boiled without salt"),
    "chickpeas": ("legume", "legume", "chickpeas (garbanzo beans bengal gram) mature seeds cooked boiled without salt"),
    "lentils": ("legume", "legume", "lentils mature seeds cooked boiled without salt"),
    "split peas": ("legume", "legume", "peas split mature seeds cooked boiled without salt"),
    "black-eyed peas": ("legume", "legume", "cowpeas common (blackeyes crowder southern) mature seeds cooked boiled without salt"),
    "lima beans": ("legume", "legume", "lima beans large mature seeds cooked boiled without salt"),
    "fava beans": ("legume", "legume", "broadbeans (fava beans) mature seeds cooked boiled without salt"),
    "mung beans": ("legume", "legume", "mung beans mature seeds cooked boiled without salt"),
    "soybeans": ("legume", "legume", "soybeans mature cooked boiled without salt"),
    "adzuki beans": ("legume", "legume", "beans adzuki mature seeds cooked boiled without salt"),
    # --- dairy ---
    "paneer": ("grilling cheese", "dairy", "paneer"),
    "halloumi": ("grilling cheese", "dairy", "halloumi"),
    "cottage cheese": ("soft dairy", "dairy", "cheese cottage lowfat 2% milkfat"),
    "greek yogurt": ("soft dairy", "dairy", "yogurt greek plain nonfat"),
    "ricotta": ("soft dairy", "dairy", "cheese ricotta part skim milk"),
}

PROTEINS = {
    name: {**PROFILES[profile], "kind": kind, "usda_query": query}
    for name, (profile, kind, query) in PROTEIN_TABLE.items()
}

# Other names people use. A general word maps to its most common cut.
PROTEIN_ALIASES = {
    "chicken": "chicken breast",
    "chicken breasts": "chicken breast",
    "chicken tenderloin": "chicken tenders",
    "chicken strips": "chicken tenders",
    "chicken thighs": "chicken thigh",
    "drumstick": "chicken drumstick",
    "chicken leg": "chicken drumstick",
    "chicken legs": "chicken drumstick",
    "wings": "chicken wings",
    "chicken wing": "chicken wings",
    "game hen": "cornish hen",
    "turkey": "ground turkey",
    "turkey leg": "turkey drumstick",
    "duck": "duck breast",
    "pigeon": "squab",
    "beef": "ground beef",
    "hamburger": "ground beef",
    "mince": "ground beef",
    "steak": "sirloin steak",
    "sirloin": "sirloin steak",
    "ribeye": "ribeye steak",
    "rib eye": "ribeye steak",
    "new york strip": "strip steak",
    "ny strip": "strip steak",
    "beef tenderloin": "filet mignon",
    "t-bone": "t-bone steak",
    "porterhouse": "porterhouse steak",
    "london broil": "flank steak",
    "hanger steak": "skirt steak",
    "cube steak": "round steak",
    "tri tip": "tri-tip",
    "rump roast": "bottom round roast",
    "pot roast": "chuck roast",
    "beef short ribs": "short ribs",
    "beef ribs": "beef back ribs",
    "stew meat": "beef stew meat",
    "stew beef": "beef stew meat",
    "liver": "beef liver",
    "veal": "veal cutlet",
    "pork": "pork chop",
    "pork chops": "pork chop",
    "ribs": "pork ribs",
    "pork rib": "pork ribs",
    "spare ribs": "pork ribs",
    "spareribs": "pork ribs",
    "st. louis ribs": "pork ribs",
    "baby backs": "baby back ribs",
    "pork butt": "pork shoulder",
    "boston butt": "pork shoulder",
    "pulled pork": "pork shoulder",
    "pancetta": "bacon",
    "sausage": "pork sausage",
    "sausages": "pork sausage",
    "brats": "bratwurst",
    "andouille": "smoked sausage",
    "hot dogs": "hot dog",
    "frankfurter": "hot dog",
    "lamb": "lamb chops",
    "lamb chop": "lamb chops",
    "mutton": "lamb shoulder",
    "deer": "venison",
    "bison": "ground bison",
    "buffalo": "ground bison",
    "boar": "wild boar",
    "sole": "flounder",
    "bass": "sea bass",
    "branzino": "sea bass",
    "barramundi": "sea bass",
    "red snapper": "snapper",
    "mahi": "mahi mahi",
    "mahi-mahi": "mahi mahi",
    "hake": "whiting",
    "swai": "catfish",
    "basa": "catfish",
    "black cod": "sablefish",
    "arctic char": "trout",
    "steelhead": "trout",
    "fresh sardines": "herring",
    "tuna": "tuna steak",
    "ahi": "tuna steak",
    "ahi tuna": "tuna steak",
    "marlin": "swordfish",
    "prawn": "shrimp",
    "langoustine": "shrimp",
    "scallop": "scallops",
    "lobster tail": "lobster",
    "crab legs": "king crab",
    "crayfish": "crawfish",
    "mussel": "mussels",
    "clam": "clams",
    "oyster": "oysters",
    "calamari": "squid",
    "escargot": "snails",
    "tinned tuna": "canned tuna",
    "sardines": "canned sardines",
    "anchovies": "canned anchovies",
    "lox": "smoked salmon",
    "crab meat": "canned crab",
    "surimi": "imitation crab",
    "turkey slices": "deli turkey",
    "roast beef": "deli roast beef",
    "egg": "eggs",
    "egg white": "egg whites",
    "firm tofu": "tofu",
    "extra-firm tofu": "tofu",
    "extra firm tofu": "tofu",
    "soft tofu": "silken tofu",
    "tvp": "soy crumbles",
    "textured vegetable protein": "soy crumbles",
    "plant-based ground": "soy crumbles",
    "veggie burgers": "veggie burger",
    "beans": "black beans",
    "cannellini beans": "white beans",
    "great northern beans": "white beans",
    "garbanzo beans": "chickpeas",
    "garbanzos": "chickpeas",
    "chickpea": "chickpeas",
    "lentil": "lentils",
    "black eyed peas": "black-eyed peas",
    "yogurt": "greek yogurt",
}
